#!/usr/bin/env bash

# Catpuccin Macchiato Pallete
rosewater=0xfff4dbd6
flamingo=0xfff0c6c6
pink=0xfff5bde6
mauve=0xffc6a0f6
red=0xffed8796
maroon=0xffee99a0
peach=0xfff5a97f
yellow=0xffeed49f
green=0xffa6da95
teal=0xff8bd5ca
sky=0xff91d7e3
sapphire=0xff7dc4e4
blue=0xff8aadf4
lavender=0xffb7bdf8
text=0xffcad3f5
subtext1=0xffb8c0e0
subtext0=0xffa5adcb
overlay2=0xff939ab7
overlay1=0xff8087a2
overlay0=0xff6e738d
surface2=0xff5b6078
surface1=0xff494d64
surface0=0xff363a4f
base=0xff24273a
mantle=0xff1e2030
crust=0xff181926
transparent=0x00000000


# Bar
## Colors
BAR_COLOR="$transparent"
BAR_BLUR_RADIUS=30

## Geometry
BAR_POSITION="top"
BAR_HEIGHT=32
BAR_PADDING=0
BAR_Y_OFFSET=11
BAR_CORNER_RADIUS=12
BAR_MARGIN=21

# Item Defaults
## Colors
BACKGROUND_COLOR="$crust"
BACKGROUND_BORDER_COLOR="$blue"
BACKGROUND_BORDER_WIDTH=0
LABEL_ALIGN="center"
LABEL_COLOR="$blue"
LABEL_HIGHLIGHT_COLOR="$red"

## Fonts
ICON_BASE_FONT="OperatorMono Nerd Font"
ICON_FONT="$ICON_BASE_FONT:Bold:17.0"
LABEL_BASE_FONT="OperatorMono Nerd Font"
LABEL_FONT="$LABEL_BASE_FONT:Bold:17.0"
LABEL_HIGHLIGHT_FONT="$LABEL_BASE_FONT:Bold:17.0"

## Geometry
BACKGROUND_CORNER_RADIUS=0
BACKGROUND_HEIGHT=32
LABEL_Y_OFFSET=1
LABEL_PADDING=10
BRACKET_BACKGROUND_BORDER_WIDTH=2
BRACKET_BACKGROUND_CORNER_RADIUS=16
