#!/usr/bin/env bash

# catppuccin macchiato colors
maroon=0xee99a0
lavender=0xb7bdf8

options=(
  active_color="$maroon"
  inactive_color="$lavender"
  hidpi=on
  style=round
  width=6.0
  blacklist=""
)

borders "${options[@]}"
