#!/usr/bin/env bash

source "$CONFIG_DIR/env.sh"

# General bar
sketchybar --bar height=34 \
  color="$TRANSPARENT" \
  position=top \
  sticky=on \
  padding_right=10 \
  padding_left=10 \
  corner_radius="$CORNER_RADIUS" \
  y_offset=8 \
  margin=12 \
  blur_radius=20 \
  notch_width=200 \
  --default updates=when_shown \
  icon.font="$FONT:Bold:$FONT_SIZE" \
  icon.color="$ICON_COLOR" \
  icon.padding_left="$PADDINGS" \
  icon.padding_right="$PADDINGS" \
  label.font="$FONT:Bold:16.0" \
  label.color="$LABEL_COLOR" \
  label.padding_left="$PADDINGS" \
  label.padding_right="$PADDINGS" \
  background.padding_right="$PADDINGS" \
  background.padding_left="$PADDINGS" \

# Left
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/spacer.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/clock.sh"

# Automatically apply configuration changes
sketchybar --hotload true

# Force all scripts to run the first time (never do this in a script)
sketchybar --update

# Initialize focused workspace
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)

