#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/catppuccin-macchiato"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_service_mode_enabled_changed
@
sketchybar --add item workspaces_spacer_left left \
           --set      workspaces_spacer_left \
                      background.drawing=off

for workspace_id in $(aerospace list-workspaces --all); do
    sketchybar --add item  space."$workspace_id" left \
               --subscribe space."$workspace_id" aerospace_workspace_change \
               --set       space."$workspace_id" \
                           background.drawing=off \
                           click_script="aerospace workspace $workspace_id" \
                           label="$workspace_id" \
                           label.width="25" \
                           script="$PLUGIN_DIR/aerospace $workspace_id"
done

sketchybar --add item  workspaces_spacer_right left \
           --set       workspaces_spacer_right \
                       background.drawing=off

sketchybar --add bracket workspaces_bracket workspaces_spacer_left '/space\..*/' workspaces_spacer_right \
           --set         workspaces_bracket \
			 background.padding_left="0" \
                         background.corner_radius="$BRACKET_BACKGROUND_CORNER_RADIUS" \
                         background.border_width="$BRACKET_BACKGROUND_BORDER_WIDTH"

